annotationtools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
import debug_toolbar

app_name = 'annotationtools'

urlpatterns = [
    url(r'^__debug__/', include(debug_toolbar.urls)),
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.login),
    path('logout/', auth_views.logout),
    path('register/', views.register, name='register'),
    path('landing/', views.landing, name='landing'),
    path('videoannotation/', include('videoannotation.urls')),
    path('imageannotation/', include('imageannotation.urls')),
    # path('objectrecognition/', include('objectrecognition.urls')),
    path('objectdetection/', include('objectdetection.urls')),
    path('upload/', include('upload_service.urls')),
    path('download/', include('download.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

download/urls.py
from django.urls import path
from . import views

app_name = 'download'

urlpatterns = [
    path('', views.datasets, name='datasets'),
    path('<str:dataset_ID>', views.labels, name='labels'),

]

videoannotation/urls.py
from django.urls import path
from . import views

app_name = 'videoannotation'

urlpatterns = [
    path('', views.datasets, name='datasets'),
    path('results/', views.results, name='results'),
    path('annotate/', views.annotate, name='annotate'),
    path('<str:datasetID>/labels/', views.labels, name='labels'),
    path('<str:datasetID>/<str:labelID>/<str:page>/', views.videodetail, name='detail')
]

videoannotation/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Video(models.Model):

    video_name = models.CharField(max_length=100)
    video_id = models.CharField(max_length=100, primary_key=True)
    source = models.CharField(max_length=100)
    duration = models.IntegerField()

    def __str__(self):
        return self.video_id


class Annotated_videos(models.Model):

    video_id = models.CharField(max_length=100, primary_key=True)
    label = models.CharField(max_length=100)
    annotated = models.BooleanField(default=False)
    validation = models.BooleanField(default=False)
    source = models.CharField(max_length=100)

    def __str__(self):
        return self.video_id


class Annotation_details(models.Model):

    user = models.ForeignKey(User, related_name='annotations', on_delete=models.CASCADE)
    validation = models.BooleanField()
    video = models.ForeignKey(Annotated_videos, on_delete=models.CASCADE, related_name='annotations')

videoannotation/views.py
from django.shortcuts import render
from django.urls import reverse

from django.shortcuts import redirect
from django.db import transaction
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from annotationtools.models import Datasets, Labels, Data, User_state, dataset_type_mapping
from django.conf import settings

import logging
logger = logging.getLogger(__name__)
ITEMS_PER_PAGE = settings.ITEMS_PER_PAGE
# Create your views here.


def setupDataset_detail(request, datasetID):
    '''
    Helper function
    '''
    dataset_ID = datasetID
    if request.session.get('dataset_ID', 0) != dataset_ID:
        request, chosen_dataset = setupDataset_labels(request, dataset_ID)
        if not chosen_dataset:
            return request, 0

    return request, request.session['dataset_ID']


def setupLabel_detail(request, labelID):
    '''
    Helper function
    '''
    if request.session.get('label_ID', 0) != labelID:
        chosen_label = Labels.objects.filter(
            dataset__dataset_ID=request.session['dataset_ID'], label_ID=labelID)
        if not chosen_label:
            return request, 0

    request.session['label_ID'] = labelID
    request.session['label_name'] = chosen_label[0].name
    return request, request.session['label_ID']


def get_dataID_from_user_state(request):
    '''
    If user_state has entry for the dataset_ID and label_ID : get state from the corresponding row
    otherwise												: create an entry and set it to lowest possible id i.e. ''
    '''
    cur_data_id = ''
    user = User.objects.filter(username=request.user.username)[:1]
    user_state = User_state.objects.filter(
        user=user, label__label_ID=request.session['label_ID'], label__dataset__dataset_ID=request.session['dataset_ID'])
    if len(user_state) < 1:
        label = Labels.objects.get(
            dataset__dataset_ID=request.session['dataset_ID'], label_ID=request.session['label_ID'])
        User_state.objects.create(user=user[0], label=label)
    else:
        cur_data_id = user_state[0].cur_data_id

    request.session['last_viewed_data_id'] = cur_data_id  # TODO: Doubt

    return request, request.session['last_viewed_data_id']


def setupSessionData(request, datasetID, labelID):
    '''
    Helper function to set session data if datasetID and labelID is valid otherwise return 0 for corresponding invalid value.
    Redirection is taken care of by videodetail()
    '''
    chosen_dataset_ID, chosen_label_ID, last_viewed_data_id = 0, 0, ''
    if datasetID == request.session.get('dataset_ID', 0) and labelID == request.session.get('label_ID', 0):
        last_viewed_data_id = request.session['last_viewed_data_id']
        return request, request.session['dataset_ID'], request.session['label_ID'], last_viewed_data_id
    elif datasetID != request.session.get('dataset_ID', 0):
        request, chosen_dataset_ID = setupDataset_detail(request, datasetID)
    else:
        chosen_dataset_ID = request.session.get('dataset_ID', 0)

    request, chosen_label_ID = setupLabel_detail(request, labelID)
    if chosen_dataset_ID != 0 and chosen_label_ID != 0:
        request, last_viewed_data_id = get_dataID_from_user_state(request)
    return request, chosen_dataset_ID, chosen_label_ID, last_viewed_data_id


def getUserMetrics(request, dataset_ID, label_ID):
    user = User.objects.filter(username=request.user.username)[:1]
    user_state = User_state.objects.filter(user=user, label__dataset__dataset_ID=dataset_ID, label__label_ID=label_ID)
    totalAnnotated = user_state[0].skip_count + user_state[0].yes_count + user_state[0].no_count
    userMetrics = {'skip_count': user_state[0].skip_count, 'yes_count': user_state[
        0].yes_count, 'no_count': user_state[0].no_count, 'totalAnnotated': totalAnnotated}
    return userMetrics


@login_required
def videodetail(request, datasetID=0, labelID=0, page='current'):
    '''
    Note: If datasetID and labelID does not match with the ones in session, they're handled helper functions.
     The value of request.session['last_viewed_data_id'] MUST be correct after the helper functions have done their job

    '''
    name = Datasets.objects.get(dataset_ID=datasetID).name
    label_ID = labelID
    dataset_ID = datasetID

    request, chosen_dataset_ID, chosen_label_ID, _ditch = setupSessionData(
        request, datasetID, labelID)
    if chosen_dataset_ID == 0:
        return redirect(reverse('videoannotation:datasets'))

    # TODO: Add indexing over video_list and annotated
    userMetrics = getUserMetrics(request, request.session['dataset_ID'], request.session['label_ID'])

    _last_viewed_video_id = request.session['last_viewed_data_id']

    data_list = Data.objects.filter(label__label_ID=label_ID, label__dataset__dataset_ID=dataset_ID,
                                    data_ID__gt=_last_viewed_video_id).order_by('data_ID')[:ITEMS_PER_PAGE]
    video_list = data_list

    response = render(request, 'videoannotation/videodetail.html', {'dataset_name':name,'videos': video_list, 'dataset_ID': request.session[
                      'dataset_ID'], 'label_ID': request.session['label_ID'], 'label_name': request.session['label_name'], 'userMetrics': userMetrics})

    if len(video_list) > 0:
        request.session['reset_cur_data_id'] = video_list[len(video_list) - 1].data_ID

    return response


@login_required
def results(request, video_id):
    '''
    Not yet implemented.

    TODO: Show some stats for annotation to the user eg, progress, skip,yes,no count across and within dataset
    '''
    video = []
    return render(request, 'videoannotation/results.html', {'video': video})


@transaction.atomic
def record_anotation(request, dataRows, annotation_response):
    '''
    1. Updates all annotation responsed into the tables: Data and User_state
    2. Update cur_data_id in the User_state

    If any of above fails, must rollback
    '''
    dataset_ID = request.session['dataset_ID']
    label_ID = request.session['label_ID']
    skip_count = 0
    yes_count = 0
    no_count = 0
    for data in dataRows:
        ann = annotation_response[data.data_ID]
        if(ann == 0):
            data.skip_count += 1
            skip_count += 1
        elif ann == 1:
            data.yes_count += 1
            yes_count += 1
        elif ann == 2:
            data.no_count += 1
            no_count += 1
        data.save()
    # Update User_state
    dataRows_count = len(dataRows)
    if dataRows_count:
        request.session['last_viewed_data_id'] = request.session['reset_cur_data_id']
        user = User.objects.filter(username=request.user.username)[:1]
        user_state = User_state.objects.filter(
            user=user, label__dataset__dataset_ID=dataset_ID, label__label_ID=label_ID).get()
        user_state.cur_data_id = request.session['last_viewed_data_id']
        user_state.skip_count = user_state.skip_count + skip_count
        user_state.yes_count = user_state.yes_count + yes_count
        user_state.no_count = user_state.no_count + no_count
        user_state.save()
    user_state = User_state.objects.filter(
        user__username=request.user.username, label__dataset__dataset_ID=dataset_ID, label__label_ID=label_ID).get()

    # TODO Add annotation_history


@login_required
def annotate(request):
    '''
    sets annotation_respond( data_id{i} : choice{i}), calls record_annotation on it and redirects next page
    '''
    annotation_response = {}
    for i in range(ITEMS_PER_PAGE):
        if 'data_id{}'.format(i + 1) in request.POST and 'choice{}'.format(i + 1) in request.POST:
            annotation_response[request.POST['data_id{}'.format(
                i + 1)]] = int(request.POST['choice{}'.format(i + 1)])
        else:
            break
    data_id_list = []
    for key, _val in annotation_response.items():
        data_id_list.append(key)

    dataRows = Data.objects.filter(label__label_ID=request.session['label_ID'], label__dataset__dataset_ID=request.session[
                                   'dataset_ID'], data_ID__in=data_id_list).order_by('data_ID')
    record_anotation(request, dataRows, annotation_response)

    # TODO: Use dajngo_bulk_update

    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.

    return redirect(reverse('videoannotation:detail', kwargs={'datasetID': request.session['dataset_ID'], 'labelID': request.session['label_ID'], 'page': 'next'}))


@login_required
def home(request):
    return render(request, 'videoannotation/home.html')


def setupDataset_labels(request, datasetID):
    '''
    If datasetID exists	: sets session variabels
            otherwise		: returns datasetID = 0
    '''
    request.session['dataset_type'] = dataset_type_mapping['VideoAnnotation']
    chosen_dataset = Datasets.objects.filter(
        dataset_type=request.session['dataset_type'], dataset_ID=datasetID)
    if chosen_dataset:
        request.session['dataset_ID'] = datasetID
        request.session['dataset_name'] = chosen_dataset[0].name
        request.session['dataset_path'] = chosen_dataset[0].path
        request.session['dataset_source'] = chosen_dataset[0].source
    else:
        return request, 0
    return request, chosen_dataset[0]


@login_required
def labels(request, datasetID=0):
    '''
    Shows labels correspondign to the datasetID if datasetID is valid exists otherwise redirects to choose dataset
    '''
    request, chosen_dataset_ID = setupDataset_labels(request, datasetID)
    if chosen_dataset_ID == 0:
        # Show some error message to user
        return redirect(reverse('videoannotation:datasets'))

    labels = []
    dataset_labels = Labels.objects.filter(
        dataset__dataset_ID=request.session['dataset_ID'])
    labels = [{'label_ID': row.label_ID, 'label_name': row.name}
              for row in dataset_labels]

videoannotation/templates/videoannotation/base.html
<head>
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'videoannotation/style.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>


<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/landing"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;Home</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block imagetype_active %}{% endblock %}">
                <a href="/imageannotation"><span class="glyphicon glyphicon-picture" aria-hidden="true"></span>&nbsp;Imageannotation</a></li>
                <li class="{% block videotype_active %}{% endblock %}"><a href="/videoannotation"><span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span>&nbsp; Videoannotation</a></li>
                <li class="{% block objecttype_active %}{% endblock %}">
                <a href="/objectdetection"><span class="glyphicon glyphicon-modal-window" aria-hidden="true"></span>&nbsp;ObjectDetection</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="/upload">
                        <span class="glyphicon glyphicon-upload" aria-hidden="true"></span>&nbsp; Upload Dataset
                    </a>
                </li>
                 <li>
                    <a href="/upload/uploaded/datasets">
                        <span class="glyphicon glyphicon-inbox" aria-hidden="true"></span>&nbsp; View your datasets
                    </a>
                </li>
                <li>
                    <a href="/download">
                        <span class="glyphicon glyphicon-download" aria-hidden="true"></span>&nbsp; Download Results
                    </a>
                </li>
                <li>
                    <a href="/">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout ({{user.username}})
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>

{% block body %}
{% endblock %}

videoannotation/templates/videoannotation/datasets.html
{% extends 'imageannotation/base.html' %}
{% block videotype_active %}active{% endblock %}

{% block body %}

<!DOCTYPE html>
<html>
<head>
    <title>Datasets</title>
</head>
<h1> Choose any one of the datasets </h1> 
<body>
	<div class="list-group" style="width: 70%; text-align: center; align-self: center;">
    {% for dataset in datasets %}
    	<a href={{ dataset.dataset_ID }}/labels/ class="list-group-item list-group-item-info" style="height: 30px; padding: 5px 15px;">{{ dataset.source }} | {{ dataset.name }}</a> <br>
    {% endfor %}
    </div>
</body>
</html>

{% endblock %}

videoannotation/templates/videoannotation/index.html
{% extends 'imageannotation/base.html' %}
{% block videotype_active %}active{% endblock %}

{% block body %}

<!DOCTYPE html>
<html>
<head>
    To LOGIN or REGISTER click <a href="/login">here</a>
</head>
{% endblock %}

videoannotation/templates/videoannotation/labels.html
{% extends 'imageannotation/base.html' %}
{% block videotype_active %}active{% endblock %}

{% block body %}

<!DOCTYPE html>
<html>
<head>
    <title>Labels</title>
</head>
<h1> Choose one of the following labels: </h1>

<body>

	<div class="list-group" style="width: 70%; text-align: center; align-self: center;">
    {% for label in labels %}
    	<a href='/videoannotation/{{datasetID}}/{{label.label_ID}}/current/' class="list-group-item list-group-item-info" style="height: 30px; padding: 5px 15px;">{{ label.label_name }}</a>
    {% endfor %}
    </div>
</body>
</html>

{% endblock %}

videoannotation/templates/videoannotation/results.html
{% extends 'imageannotation/base.html' %}
{% block videotype_active %}active{% endblock %}

{% block body %}

<h1>Annotation done</h1>

{% endblock %}

videoannotation/templates/videoannotation/videodetail.html
{% extends 'imageannotation/base.html' %}
{% block videotype_active %}active{% endblock %}

{% block body %}

<!DOCTYPE html>
<html>
<head>
    <title>Videos</title>
</head>
<body>
    <div style="position:fixed; top:10%; right:2%; background-color:lightblue;">
      <h5>User metrics</h5>
      <h6>Skipped: {{ userMetrics.skip_count }}</h6>
      <h6>Yes: {{ userMetrics.yes_count }}</h6>
      <h6>No: {{ userMetrics.no_count }}</h6>
      <h6>Total Annotated: {{ userMetrics.totalAnnotated }}</h6>
    </div>
</body>
<form action="{% url 'videoannotation:annotate' %}" method="post">
{% csrf_token %}

{% for video in videos %}
	<h1> Video Id :{{ video.data_ID }} </h1>
	<video width="400" height="300" controls autoplay loop>
	  <source src="{{MEDIA_URL}}{{ dataset_ID }}/{{dataset_name}}/{{ video.data_ID }}" type="video/mp4"> </source>
	</video>
	</body>
	</html>

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
   <h1> TAG :{{ dataset_name }} : {{ label_name }} </h1>
   <input type="hidden" value = "{{video.data_ID}}" name = "data_id{{forloop.counter}}" />
   <input type="radio" name="choice{{forloop.counter}}" id='0' value='0' checked="checked">
   <label for='0'>SKIP</label><br />
	 <input type="radio" name="choice{{forloop.counter}}" id="1" value="1" />
	 <label for="1">TRUE</label><br />
   <input type="radio" name="choice{{forloop.counter}}" id="2" value="2" />
   <label for="2">FALSE</label><br />

{% endfor %}	
{% if not videos %}
  <h3>Seems like there's no more data for your choice</h3>
{% endif %}
{% if videos %}
  <input type= "submit" value="validate">
{% endif %}
</form>


{% endblock %}
<!-- <div>

  {% if show_next %}
  <a href="/videoannotation/{{dataset_ID}}/{{label_ID}}/next"> next</a>
  {% endif %}
</div>
 -->