annotationtools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
import debug_toolbar

app_name = 'annotationtools'

urlpatterns = [
    url(r'^__debug__/', include(debug_toolbar.urls)),
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.login),
    path('logout/', auth_views.logout),
    path('register/', views.register, name='register'),
    path('landing/', views.landing, name='landing'),
    path('videoannotation/', include('videoannotation.urls')),
    path('imageannotation/', include('imageannotation.urls')),
    # path('objectrecognition/', include('objectrecognition.urls')),
    path('objectdetection/', include('objectdetection.urls')),
    path('upload/', include('upload_service.urls')),
    path('download/', include('download.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

download/urls.py
from django.urls import path
from . import views

app_name = 'download'

urlpatterns = [
    path('', views.datasets, name='datasets'),
    path('<str:dataset_ID>', views.labels, name='labels'),

]

imageannotation/urls.py
from django.urls import path
from . import views

app_name = 'imageannotation'

urlpatterns = [
    path('', views.datasets, name='datasets'),
    path('<str:datasetID>/labels/', views.labels, name='labels'),
    path('<str:datasetID>/<str:labelID>/<str:page>/', views.imagedetail, name='detail'),
    path('annotate/', views.annotate, name='annotate'),
    path('results/', views.results, name='results'),
]

imageannotation/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

imageannotation/views.py
from django.shortcuts import render
from django.http import HttpResponse
from annotationtools.models import Datasets, Labels, Data, User_state, dataset_type_mapping
from django.urls import reverse

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.db import transaction
from django.conf import settings
import logging
logger = logging.getLogger(__name__)

ITEMS_PER_PAGE = settings.ITEMS_PER_PAGE


# print(User.objects.all())
@login_required(login_url='/login/')
def datasets(request):
    request = setupSession(request)
    request, datasets = setupDatasetType(request, dataset_type=dataset_type_mapping['ImageAnnotation'])
    # datasets = [{ 'dataset_ID' : 'sasdsd',  'dataset_name' : 'sasdsd'}]
    return render(request, 'imageannotation/datasets.html', {'datasets': datasets})


def setupSession(request):
    request.session['dataset_type'] = 1
    request.session['label_ID'] = 0
    request.session['dataset_ID'] = 0
    request.session['last_viewed_data_id'] = ''

    return request


def setupDatasetType(request, dataset_type):
    datasets = Datasets.objects.filter(dataset_type=dataset_type)
    request.session['dataset_type'] = dataset_type
    return request, datasets


@login_required
def labels(request, datasetID=0):
    request, chosen_dataset_ID = setupDataset_labels(request, datasetID)
    if chosen_dataset_ID == 0:
        return redirect(reverse('imageannotation:datasets'))  # Show some error message to user

    labels = []
    dataset_labels = Labels.objects.filter(dataset__dataset_ID=request.session['dataset_ID'])
    labels = [{'label_ID': row.label_ID, 'label_name': row.name} for row in dataset_labels]
    return render(request, 'imageannotation/labels.html', {'dataset_name': request.session['dataset_name'], 'datasetID': request.session['dataset_ID'], 'labels': labels})


def setupDataset_labels(request, datasetID):
    '''
    If datasetID exists	: sets session variabels
            otherwise		: returns datasetID = 0
    '''
    request.session['dataset_type'] = dataset_type_mapping['ImageAnnotation']
    chosen_dataset = Datasets.objects.filter(dataset_type=request.session['dataset_type'], dataset_ID=datasetID)
    if chosen_dataset:
        request.session['dataset_ID'] = datasetID
        request.session['dataset_name'] = chosen_dataset[0].name
        request.session['dataset_path'] = chosen_dataset[0].path
        request.session['dataset_source'] = chosen_dataset[0].source
    else:
        return request, 0
    return request, chosen_dataset[0]


def getUserMetrics(request, dataset_ID, label_ID):
    user = User.objects.filter(username=request.user.username)[:1]
    user_state = User_state.objects.filter(user=user, label__dataset__dataset_ID=dataset_ID, label__label_ID=label_ID)
    totalAnnotated = user_state[0].skip_count + user_state[0].yes_count + user_state[0].no_count
    userMetrics = {'skip_count': user_state[0].skip_count, 'yes_count': user_state[
        0].yes_count, 'no_count': user_state[0].no_count, 'totalAnnotated': totalAnnotated}
    return userMetrics


@login_required
def imagedetail(request, datasetID='none', labelID='none', page='current'):
    ''' TODO : change default values to in type and take care of conditions

    '''
    name = Datasets.objects.get(dataset_ID=datasetID).name
    label_ID = labelID
    dataset_ID = datasetID

    request, chosen_dataset_ID, chosen_label_ID, _ditch = setupSessionData(request, datasetID, labelID)
    # print(chosen_dataset)
    if chosen_dataset_ID == 0:
        return redirect(reverse('imageannotation:datasets'))
    if chosen_label_ID == 0:
        return redirect(reverse('imageannotation:labels', kwargs={'datasetID': request.session['dataset_ID']}))

    userMetrics = getUserMetrics(request, request.session['dataset_ID'], request.session['label_ID'])

    # request, chosen_label = setupLabel(request, labelID)
    # # print(chosen_label)
    # if chosen_label == 'none':
    # 	return redirect(reverse('imageannotation/'+request.session['dataset_ID']+'/labels'))

    _last_viewed_image_id = request.session['last_viewed_data_id']

    data_list = Data.objects.filter(label__label_ID=label_ID, label__dataset__dataset_ID=dataset_ID,
                                    data_ID__gt=_last_viewed_image_id).order_by('data_ID')[:ITEMS_PER_PAGE]
    image_list = data_list

    show_next = 1
    if len(image_list) < 1:
        show_next = 0
    print('dadfdf', dataset_ID, name)
    response = render(request, 'imageannotation/imagedetail.html', {'dataset_name':name,'images': image_list, 'show_next': show_next, 'dataset_ID': request.session[
                      'dataset_ID'], 'label_ID': request.session['label_ID'], 'label_name': request.session['label_name'], 'userMetrics': userMetrics})

    if len(image_list) > 0:
        request.session['reset_cur_data_id'] = image_list[len(image_list) - 1].data_ID

    return response


def setupSessionData(request, datasetID, labelID):
    '''
    Helper function to set session data if datasetID and labelID is valid otherwise return 0 for corresponding invalid value.
    Redirection is taken care of by videodetail()
    '''
    chosen_dataset_ID, chosen_label_ID, last_viewed_data_id = 0, 0, ''
    if datasetID == request.session.get('dataset_ID', 0) and labelID == request.session.get('label_ID', 0):
        last_viewed_data_id = request.session['last_viewed_data_id']
        return request, request.session['dataset_ID'], request.session['label_ID'], last_viewed_data_id
    elif datasetID != request.session.get('dataset_ID', 0):
        request, chosen_dataset_ID = setupDataset_detail(request, datasetID)
    else:
        chosen_dataset_ID = request.session.get('dataset_ID', 0)

    request, chosen_label_ID = setupLabel_detail(request, labelID)
    if chosen_dataset_ID != 0 and chosen_label_ID != 0:
        request, last_viewed_data_id = get_dataID_from_user_state(request)
    return request, chosen_dataset_ID, chosen_label_ID, last_viewed_data_id


def setupDataset_detail(request, datasetID):
    dataset_ID = datasetID
    # print("setupDataset_detail")
    if request.session.get('dataset_ID', 0) != dataset_ID:
        request, chosen_dataset = setupDataset_labels(request, dataset_ID)
        # print(chosen_dataset, "setupDataset_detail")
        if not chosen_dataset:
            return request, 0

    return request, request.session['dataset_ID']


# print(request.user.username)
def setupLabel_detail(request, labelID):
    '''
    Helper function
    '''
    chosen_label = Labels.objects.filter(dataset__dataset_ID=request.session['dataset_ID'], label_ID=labelID)
    # chosen_label=[]
    if request.session.get('label_ID', 0) != labelID:
        if not chosen_label:
            return request, 0

    request.session['label_ID'] = labelID
    request.session['label_name'] = chosen_label[0].name
    return request, request.session['label_ID']


def get_dataID_from_user_state(request):
    '''
    If user_state has entry for the dataset_ID and label_ID : get state from the corresponding row
    otherwise												: create an entry and set it to lowest possible id i.e. ''
    '''
    cur_data_id = ''
    user = User.objects.filter(username=request.user.username)[:1]
    user_state = User_state.objects.filter(user=user, label__label_ID=request.session['label_ID'], label__dataset__dataset_ID=request.session['dataset_ID'])
    if len(user_state) < 1:
        label = Labels.objects.get(dataset__dataset_ID=request.session['dataset_ID'], label_ID=request.session['label_ID'])
        User_state.objects.create(user=user[0], label=label)
    else:
        cur_data_id = user_state[0].cur_data_id

    request.session['last_viewed_data_id'] = cur_data_id  # TODO: Doubt

    return request, request.session['last_viewed_data_id']


@login_required
def annotate(request):
    # selected_choice = {}

    annotation_response = {}
    for i in range(ITEMS_PER_PAGE):
        if 'data_id{}'.format(i + 1) in request.POST and 'choice{}'.format(i + 1) in request.POST:
            annotation_response[request.POST['data_id{}'.format(i + 1)]] = int(request.POST['choice{}'.format(i + 1)])
        else:
            break
    data_id_list = []
    for key, _val in annotation_response.items():
        data_id_list.append(key)

    dataRows = Data.objects.filter(label__label_ID=request.session['label_ID'], label__dataset__dataset_ID=request.session[
                                   'dataset_ID'], data_ID__in=data_id_list).order_by('data_ID')
    record_anotation(request, dataRows, annotation_response)
    # print(type(request.session['dataset_ID']))
    return redirect(reverse('imageannotation:detail', kwargs={'datasetID': request.session['dataset_ID'], 'labelID': request.session['label_ID'], 'page': 'next'}))


@transaction.atomic
def record_anotation(request, dataRows, annotation_response):

    dataset_ID = request.session['dataset_ID']
    label_ID = request.session['label_ID']
    skip_count = 0
    yes_count = 0
    no_count = 0
    for data in dataRows:
        ann = annotation_response[data.data_ID]
        if(ann == 0):
            data.skip_count += 1
            skip_count += 1
        elif ann == 1:
            data.yes_count += 1
            yes_count += 1
        elif ann == 2:
            data.no_count += 1
            no_count += 1
        data.save()
    # Update User_state
    dataRows_count = len(dataRows)
    if dataRows_count:
        request.session['last_viewed_data_id'] = request.session['reset_cur_data_id']
        user = User.objects.filter(username=request.user.username)[:1]
        user_state = User_state.objects.filter(
            user=user, label__dataset__dataset_ID=dataset_ID, label__label_ID=label_ID).get()
        user_state.cur_data_id = request.session['last_viewed_data_id']
        user_state.skip_count = user_state.skip_count + skip_count

imageannotation/templates/imageannotation/base.html
<head>
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'imageannotation/style.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>


<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/landing"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;Home</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block imagetype_active %}{% endblock %}">
                <a href="/imageannotation"><span class="glyphicon glyphicon-picture" aria-hidden="true"></span>&nbsp;Imageannotation</a></li>
                <li class="{% block videotype_active %}{% endblock %}"><a href="/videoannotation"><span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span>&nbsp; Videoannotation</a></li>
                <li class="{% block objecttype_active %}{% endblock %}">
                <a href="/objectdetection"><span class="glyphicon glyphicon-modal-window" aria-hidden="true"></span>&nbsp;ObjectDetection</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="/upload">
                        <span class="glyphicon glyphicon-upload" aria-hidden="true"></span>&nbsp; Upload Dataset
                    </a>
                </li>
                <li>
                    <a href="/upload/uploaded/datasets">
                        <span class="glyphicon glyphicon-inbox" aria-hidden="true"></span>&nbsp; View your datasets
                    </a>
                </li>
                <li>
                    <a href="/download">
                        <span class="glyphicon glyphicon-download" aria-hidden="true"></span>&nbsp; Download Results
                    </a>
                </li>
                <li>
                    <a href="/logout">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout ({{user.username}})
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>

{% block body %}
{% endblock %}

imageannotation/templates/imageannotation/datasets.html
{% extends 'imageannotation/base.html' %}
{% block imagetype_active %}active{% endblock %}

{% block body %}

<html>
	<head>
    	<title>Object Recognition Datasets</title>
	</head>
	<h1> Choose any one of the datasets </h1> 
<body>

	<div class="list-group" style="width: 70%;text-align: center; align-self: center;">
    {% for dataset in datasets %}
        <a href="{{ dataset.dataset_ID }}/labels/" class="list-group-item list-group-item-info" style="height: 30px; padding: 5px 15px;">{{ dataset.source }} | {{ dataset.name }}</a>
    {% endfor %}
    </div>

</body>
</html>


{% endblock %}

imageannotation/templates/imageannotation/imagedetail.html
{% extends 'imageannotation/base.html' %}
{% block imagetype_active %}active{% endblock %}

{% block body %}


<!DOCTYPE html>
<html>
<head>
    <title>Images</title>
</head>
<body>
    <div style="position:fixed; top:10%; right:2%; background-color:lightblue">
      <h5>User metrics</h5>
      <h6>Skipped: {{ userMetrics.skip_count }}</h6>
      <h6>Yes: {{ userMetrics.yes_count }}</h6>
      <h6>No: {{ userMetrics.no_count }}</h6>
      <h6>Total Annotated: {{ userMetrics.totalAnnotated }}</h6>
    </div>
</body>
<form action="{% url 'imageannotation:annotate' %}" method="post">
{% csrf_token %}

{% for image in images %}
	<h1> Image Id :{{ image.data_ID }} </h1>
	 <img src="{{MEDIA_URL}}{{ dataset_ID }}/{{dataset_name}}/{{ image.data_ID }}" style="width:300px;height:300px;"> 
	</body>
	</html>

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
   <h1> TAG :{{ label_name }} </h1>
   <input type="hidden" value = "{{image.data_ID}}" name = "data_id{{forloop.counter}}" />
   <input type="radio" name="choice{{forloop.counter}}" id='0' value='0' checked="checked">
   <label for='0'>SKIP</label><br />
	 <input type="radio" name="choice{{forloop.counter}}" id="1" value="1" />
	 <label for="1">TRUE</label><br />
   <input type="radio" name="choice{{forloop.counter}}" id="2" value="2" />
   <label for="2">FALSE</label><br />

{% endfor %}	
{% if not images %}
  <h3>Seems like there's no more data for your choice</h3>
{% endif %}
{% if images %}
  <input type= "submit" value="validate">
{% endif %}
</form>

{% endblock %}

<!-- <div>

  {% if show_next %}
  <a href="/imageannotation/{{dataset_ID}}/{{label_ID}}/next"> next</a>
  {% endif %}
</div>
 -->

imageannotation/templates/imageannotation/labels.html
{% extends 'imageannotation/base.html' %}
{% block imagetype_active %}active{% endblock %}

{% block body %}


<head>
    <title>Labels</title>

<h1> Choose one of the following labels: </h1>
<head>
    <title>Labels</title>
</head>
<body>
	<div class="list-group" style="width: 70%; text-align: center; align-self: center;">
    {% for label in labels %}
        <a href='/imageannotation/{{datasetID}}/{{label.label_ID}}/current/' class="list-group-item list-group-item-info" style="height: 30px; padding: 5px 15px;">{{ label.label_name }}</a>
    {% endfor %}
    </div>
</body>
</html>


{% endblock %}